2024-11-14 14:48:57,502 p=2429 u=sarthak n=ansible | PLAY [Execute system commands] ****************************************************************************************************************************************************
2024-11-14 14:48:57,505 p=2429 u=sarthak n=ansible | TASK [Gathering Facts] ************************************************************************************************************************************************************
2024-11-14 14:48:58,573 p=2429 u=sarthak n=ansible | [WARNING]: Platform linux on host v1 is using the discovered Python interpreter at /usr/bin/python3.9, but future installation of another Python interpreter could change the
meaning of that path. See https://docs.ansible.com/ansible-core/2.17/reference_appendices/interpreter_discovery.html for more information.

2024-11-14 14:48:58,573 p=2429 u=sarthak n=ansible | ok: [v1]
2024-11-14 14:48:58,578 p=2429 u=sarthak n=ansible | TASK [Run system commands and get output] *****************************************************************************************************************************************
2024-11-14 14:48:58,964 p=2429 u=sarthak n=ansible | ok: [v1]
2024-11-14 14:48:58,968 p=2429 u=sarthak n=ansible | TASK [Show the result] ************************************************************************************************************************************************************
2024-11-14 14:48:58,980 p=2429 u=sarthak n=ansible | ok: [v1] => {
    "result": {
        "changed": false,
        "failed": false,
        "result": {
            "Architecture": "aarch64",
            "Filesystem Disk Space": {
                "avail": "9.2G",
                "filesystem": "/dev/mapper/rhel-root",
                "mounted_on": "/",
                "size": "17G",
                "status": true,
                "use_percent": "45%",
                "used": "7.3G"
            },
            "Filesystem Type": "xfs",
            "Java Version": "Error: Command failed with no stderr output.",
            "OS Release Info": {
                "os_name": "Red Hat Enterprise Linux",
                "os_version": "9.4"
            },
            "compatibility": {
                "compatible": false,
                "details": [
                    "Incompatible architecture. x86_64 required.",
                    "Invalid or empty disk space output."
                ],
                "reason": "Incompatible system."
            }
        }
    }
}
2024-11-14 14:48:58,987 p=2429 u=sarthak n=ansible | PLAY RECAP ************************************************************************************************************************************************************************
2024-11-14 14:48:58,987 p=2429 u=sarthak n=ansible | v1                         : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-14 14:52:12,375 p=2511 u=sarthak n=ansible | PLAY [Execute system commands] ****************************************************************************************************************************************************
2024-11-14 14:52:12,378 p=2511 u=sarthak n=ansible | TASK [Gathering Facts] ************************************************************************************************************************************************************
2024-11-14 14:52:13,429 p=2511 u=sarthak n=ansible | [WARNING]: Platform linux on host v1 is using the discovered Python interpreter at /usr/bin/python3.9, but future installation of another Python interpreter could change the
meaning of that path. See https://docs.ansible.com/ansible-core/2.17/reference_appendices/interpreter_discovery.html for more information.

2024-11-14 14:52:13,429 p=2511 u=sarthak n=ansible | ok: [v1]
2024-11-14 14:52:13,434 p=2511 u=sarthak n=ansible | TASK [Run system commands and get output] *****************************************************************************************************************************************
2024-11-14 14:52:13,808 p=2511 u=sarthak n=ansible | ok: [v1]
2024-11-14 14:52:13,810 p=2511 u=sarthak n=ansible | TASK [Show the result] ************************************************************************************************************************************************************
2024-11-14 14:52:13,822 p=2511 u=sarthak n=ansible | ok: [v1] => {
    "result": {
        "changed": false,
        "failed": false,
        "result": {
            "Architecture": "aarch64",
            "Filesystem Disk Space": {
                "avail": "9.2G",
                "filesystem": "/dev/mapper/rhel-root",
                "mounted_on": "/",
                "size": "17G",
                "status": true,
                "use_percent": "45%",
                "used": "7.3G"
            },
            "Filesystem Type": "xfs",
            "Java Version": "Error: Command failed with no stderr output.",
            "OS Release Info": {
                "os_name": "Red Hat Enterprise Linux",
                "os_version": "9.4"
            },
            "compatibility": {
                "compatible": false,
                "details": [
                    "Incompatible architecture. x86_64 required.",
                    "Invalid or empty disk space output."
                ],
                "reason": "Incompatible system."
            }
        }
    }
}
2024-11-14 14:52:13,828 p=2511 u=sarthak n=ansible | PLAY RECAP ************************************************************************************************************************************************************************
2024-11-14 14:52:13,828 p=2511 u=sarthak n=ansible | v1                         : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-14 14:52:36,726 p=2574 u=sarthak n=ansible | PLAY [Execute system commands] ****************************************************************************************************************************************************
2024-11-14 14:52:36,729 p=2574 u=sarthak n=ansible | TASK [Gathering Facts] ************************************************************************************************************************************************************
2024-11-14 14:52:37,581 p=2574 u=sarthak n=ansible | [WARNING]: Platform linux on host v1 is using the discovered Python interpreter at /usr/bin/python3.9, but future installation of another Python interpreter could change the
meaning of that path. See https://docs.ansible.com/ansible-core/2.17/reference_appendices/interpreter_discovery.html for more information.

2024-11-14 14:52:37,581 p=2574 u=sarthak n=ansible | ok: [v1]
2024-11-14 14:52:37,587 p=2574 u=sarthak n=ansible | TASK [Run system commands and get output] *****************************************************************************************************************************************
2024-11-14 14:52:37,974 p=2574 u=sarthak n=ansible | ok: [v1]
2024-11-14 14:52:37,977 p=2574 u=sarthak n=ansible | TASK [Show the result] ************************************************************************************************************************************************************
2024-11-14 14:52:37,987 p=2574 u=sarthak n=ansible | ok: [v1] => {
    "result": {
        "changed": false,
        "failed": false,
        "result": {
            "Architecture": "aarch64",
            "Filesystem Disk Space": {
                "avail": "9.2G",
                "filesystem": "/dev/mapper/rhel-root",
                "mounted_on": "/",
                "size": "17G",
                "status": true,
                "use_percent": "45%",
                "used": "7.3G"
            },
            "Filesystem Type": "xfs",
            "Java Version": "Error: Command failed with no stderr output.",
            "OS Release Info": {
                "os_name": "Red Hat Enterprise Linux",
                "os_version": "9.4"
            },
            "compatibility": {
                "compatible": false,
                "details": [
                    "Incompatible architecture. x86_64 required.",
                    "Invalid or empty disk space output."
                ],
                "reason": "Incompatible system."
            }
        }
    }
}
2024-11-14 14:52:37,993 p=2574 u=sarthak n=ansible | PLAY RECAP ************************************************************************************************************************************************************************
2024-11-14 14:52:37,993 p=2574 u=sarthak n=ansible | v1                         : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-14 14:53:28,785 p=2633 u=sarthak n=ansible | PLAY [Execute system commands] ****************************************************************************************************************************************************
2024-11-14 14:53:28,789 p=2633 u=sarthak n=ansible | TASK [Gathering Facts] ************************************************************************************************************************************************************
2024-11-14 14:53:29,626 p=2633 u=sarthak n=ansible | [WARNING]: Platform linux on host v1 is using the discovered Python interpreter at /usr/bin/python3.9, but future installation of another Python interpreter could change the
meaning of that path. See https://docs.ansible.com/ansible-core/2.17/reference_appendices/interpreter_discovery.html for more information.

2024-11-14 14:53:29,627 p=2633 u=sarthak n=ansible | ok: [v1]
2024-11-14 14:53:29,632 p=2633 u=sarthak n=ansible | TASK [Run system commands and get output] *****************************************************************************************************************************************
2024-11-14 14:53:30,007 p=2633 u=sarthak n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: 'stream' or 'filename' should not be specified together with 'handlers'
2024-11-14 14:53:30,008 p=2633 u=sarthak n=ansible | fatal: [v1]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 172.16.7.128 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ansibleuser/.ansible/tmp/ansible-tmp-1731576209.684968-2654-150403943728389/AnsiballZ_install_ba_client.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ansibleuser/.ansible/tmp/ansible-tmp-1731576209.684968-2654-150403943728389/AnsiballZ_install_ba_client.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ansibleuser/.ansible/tmp/ansible-tmp-1731576209.684968-2654-150403943728389/AnsiballZ_install_ba_client.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.install_ba_client', init_globals=dict(_module_fqn='ansible.modules.install_ba_client', _modlib_path=modlib_path),\r\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_install_ba_client_payload_ctxypuix/ansible_install_ba_client_payload.zip/ansible/modules/install_ba_client.py\", line 4, in <module>\r\n  File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\r\n  File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 664, in _load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 627, in _load_backward_compatible\r\n  File \"<frozen zipimport>\", line 259, in load_module\r\n  File \"/tmp/ansible_install_ba_client_payload_ctxypuix/ansible_install_ba_client_payload.zip/ansible/module_utils/install_ba_client_utils.py\", line 5, in <module>\r\n  File \"/usr/lib64/python3.9/logging/__init__.py\", line 1995, in basicConfig\r\n    raise ValueError(\"'stream' or 'filename' should not be \"\r\nValueError: 'stream' or 'filename' should not be specified together with 'handlers'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-14 14:53:30,008 p=2633 u=sarthak n=ansible | PLAY RECAP ************************************************************************************************************************************************************************
2024-11-14 14:53:30,009 p=2633 u=sarthak n=ansible | v1                         : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-14 14:55:33,713 p=2762 u=sarthak n=ansible | PLAY [Execute system commands] ****************************************************************************************************************************************************
2024-11-14 14:55:33,717 p=2762 u=sarthak n=ansible | TASK [Gathering Facts] ************************************************************************************************************************************************************
2024-11-14 14:55:34,772 p=2762 u=sarthak n=ansible | [WARNING]: Platform linux on host v1 is using the discovered Python interpreter at /usr/bin/python3.9, but future installation of another Python interpreter could change the
meaning of that path. See https://docs.ansible.com/ansible-core/2.17/reference_appendices/interpreter_discovery.html for more information.

2024-11-14 14:55:34,772 p=2762 u=sarthak n=ansible | ok: [v1]
2024-11-14 14:55:34,777 p=2762 u=sarthak n=ansible | TASK [Run system commands and get output] *****************************************************************************************************************************************
2024-11-14 14:55:35,158 p=2762 u=sarthak n=ansible | ok: [v1]
2024-11-14 14:55:35,160 p=2762 u=sarthak n=ansible | TASK [Show the result] ************************************************************************************************************************************************************
2024-11-14 14:55:35,172 p=2762 u=sarthak n=ansible | ok: [v1] => {
    "result": {
        "changed": false,
        "failed": false,
        "result": {
            "Architecture": "aarch64",
            "Filesystem Disk Space": {
                "avail": "9.2G",
                "filesystem": "/dev/mapper/rhel-root",
                "mounted_on": "/",
                "size": "17G",
                "status": true,
                "use_percent": "45%",
                "used": "7.3G"
            },
            "Filesystem Type": "xfs",
            "Java Version": "Error: Command failed with no stderr output.",
            "OS Release Info": {
                "os_name": "Red Hat Enterprise Linux",
                "os_version": "9.4"
            },
            "compatibility": {
                "compatible": false,
                "details": [
                    "Incompatible architecture. x86_64 required.",
                    "Invalid or empty disk space output."
                ],
                "reason": "Incompatible system."
            }
        }
    }
}
2024-11-14 14:55:35,179 p=2762 u=sarthak n=ansible | PLAY RECAP ************************************************************************************************************************************************************************
2024-11-14 14:55:35,179 p=2762 u=sarthak n=ansible | v1                         : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-14 15:02:52,171 p=2854 u=sarthak n=ansible | PLAY [Execute system commands] ****************************************************************************************************************************************************
2024-11-14 15:02:52,174 p=2854 u=sarthak n=ansible | TASK [Gathering Facts] ************************************************************************************************************************************************************
2024-11-14 15:02:53,271 p=2854 u=sarthak n=ansible | [WARNING]: Platform linux on host v1 is using the discovered Python interpreter at /usr/bin/python3.9, but future installation of another Python interpreter could change the
meaning of that path. See https://docs.ansible.com/ansible-core/2.17/reference_appendices/interpreter_discovery.html for more information.

2024-11-14 15:02:53,272 p=2854 u=sarthak n=ansible | ok: [v1]
2024-11-14 15:02:53,277 p=2854 u=sarthak n=ansible | TASK [Run system commands and get output] *****************************************************************************************************************************************
2024-11-14 15:02:53,668 p=2854 u=sarthak n=ansible | ok: [v1]
2024-11-14 15:02:53,671 p=2854 u=sarthak n=ansible | TASK [Show the result] ************************************************************************************************************************************************************
2024-11-14 15:02:53,682 p=2854 u=sarthak n=ansible | ok: [v1] => {
    "result": {
        "changed": false,
        "failed": false,
        "result": {
            "Architecture": "aarch64",
            "Filesystem Disk Space": {
                "avail": "9.2G",
                "filesystem": "/dev/mapper/rhel-root",
                "mounted_on": "/",
                "size": "17G",
                "status": true,
                "use_percent": "45%",
                "used": "7.3G"
            },
            "Filesystem Type": "xfs",
            "Java Version": "Error: Command failed with no stderr output.",
            "OS Release Info": {
                "os_name": "Red Hat Enterprise Linux",
                "os_version": "9.4"
            },
            "compatibility": {
                "compatible": false,
                "details": [
                    "Incompatible architecture. x86_64 required.",
                    "Invalid or empty disk space output."
                ],
                "reason": "Incompatible system."
            }
        }
    }
}
2024-11-14 15:02:53,688 p=2854 u=sarthak n=ansible | PLAY RECAP ************************************************************************************************************************************************************************
2024-11-14 15:02:53,688 p=2854 u=sarthak n=ansible | v1                         : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-14 15:03:12,064 p=2918 u=sarthak n=ansible | PLAY [Execute system commands] ****************************************************************************************************************************************************
2024-11-14 15:03:12,067 p=2918 u=sarthak n=ansible | TASK [Gathering Facts] ************************************************************************************************************************************************************
2024-11-14 15:03:12,914 p=2918 u=sarthak n=ansible | [WARNING]: Platform linux on host v1 is using the discovered Python interpreter at /usr/bin/python3.9, but future installation of another Python interpreter could change the
meaning of that path. See https://docs.ansible.com/ansible-core/2.17/reference_appendices/interpreter_discovery.html for more information.

2024-11-14 15:03:12,914 p=2918 u=sarthak n=ansible | ok: [v1]
2024-11-14 15:03:12,920 p=2918 u=sarthak n=ansible | TASK [Run system commands and get output] *****************************************************************************************************************************************
2024-11-14 15:03:13,302 p=2918 u=sarthak n=ansible | ok: [v1]
2024-11-14 15:03:13,306 p=2918 u=sarthak n=ansible | TASK [Show the result] ************************************************************************************************************************************************************
2024-11-14 15:03:13,317 p=2918 u=sarthak n=ansible | ok: [v1] => {
    "result": {
        "changed": false,
        "failed": false,
        "result": {
            "Architecture": "aarch64",
            "Filesystem Disk Space": {
                "avail": "9.2G",
                "filesystem": "/dev/mapper/rhel-root",
                "mounted_on": "/",
                "size": "17G",
                "status": true,
                "use_percent": "45%",
                "used": "7.3G"
            },
            "Filesystem Type": "xfs",
            "Java Version": "Error: Command failed with no stderr output.",
            "OS Release Info": {
                "os_name": "Red Hat Enterprise Linux",
                "os_version": "9.4"
            },
            "compatibility": {
                "compatible": false,
                "details": [
                    "Incompatible architecture. x86_64 required."
                ],
                "reason": "Incompatible system."
            }
        }
    }
}
2024-11-14 15:03:13,325 p=2918 u=sarthak n=ansible | PLAY RECAP ************************************************************************************************************************************************************************
2024-11-14 15:03:13,325 p=2918 u=sarthak n=ansible | v1                         : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-14 15:03:31,745 p=2975 u=sarthak n=ansible | PLAY [Execute system commands] ****************************************************************************************************************************************************
2024-11-14 15:03:31,753 p=2975 u=sarthak n=ansible | TASK [Gathering Facts] ************************************************************************************************************************************************************
2024-11-14 15:03:33,505 p=2975 u=sarthak n=ansible | [WARNING]: Platform linux on host v1 is using the discovered Python interpreter at /usr/bin/python3.9, but future installation of another Python interpreter could change the
meaning of that path. See https://docs.ansible.com/ansible-core/2.17/reference_appendices/interpreter_discovery.html for more information.

2024-11-14 15:03:33,505 p=2975 u=sarthak n=ansible | ok: [v1]
2024-11-14 15:04:01,129 p=2975 u=sarthak n=ansible | [WARNING]: Platform linux on host v2 is using the discovered Python interpreter at /usr/bin/python3.11, but future installation of another Python interpreter could change the
meaning of that path. See https://docs.ansible.com/ansible-core/2.17/reference_appendices/interpreter_discovery.html for more information.

2024-11-14 15:04:01,130 p=2975 u=sarthak n=ansible | ok: [v2]
2024-11-14 15:04:01,143 p=2975 u=sarthak n=ansible | TASK [Run system commands and get output] *****************************************************************************************************************************************
2024-11-14 15:04:01,559 p=2975 u=sarthak n=ansible | ok: [v1]
2024-11-14 15:04:15,392 p=2975 u=sarthak n=ansible | ok: [v2]
2024-11-14 15:04:15,399 p=2975 u=sarthak n=ansible | TASK [Show the result] ************************************************************************************************************************************************************
2024-11-14 15:04:15,416 p=2975 u=sarthak n=ansible | ok: [v1] => {
    "result": {
        "changed": false,
        "failed": false,
        "result": {
            "Architecture": "aarch64",
            "Filesystem Disk Space": {
                "avail": "9.2G",
                "filesystem": "/dev/mapper/rhel-root",
                "mounted_on": "/",
                "size": "17G",
                "status": true,
                "use_percent": "45%",
                "used": "7.3G"
            },
            "Filesystem Type": "xfs",
            "Java Version": "Error: Command failed with no stderr output.",
            "OS Release Info": {
                "os_name": "Red Hat Enterprise Linux",
                "os_version": "9.4"
            },
            "compatibility": {
                "compatible": false,
                "details": [
                    "Incompatible architecture. x86_64 required."
                ],
                "reason": "Incompatible system."
            }
        }
    }
}
2024-11-14 15:04:15,422 p=2975 u=sarthak n=ansible | ok: [v2] => {
    "result": {
        "changed": false,
        "failed": false,
        "result": {
            "Architecture": "x86_64",
            "Filesystem Disk Space": {
                "avail": "79G",
                "filesystem": "/dev/mapper/rhel-root",
                "mounted_on": "/",
                "size": "91G",
                "status": true,
                "use_percent": "14%",
                "used": "12G"
            },
            "Filesystem Type": "xfs",
            "Java Version": "java version \"1.8.0_421\"",
            "OS Release Info": {
                "os_name": "Red Hat Enterprise Linux",
                "os_version": "8.10"
            },
            "compatibility": {
                "compatible": true,
                "reason": "System is compatible."
            }
        }
    }
}
2024-11-14 15:04:15,437 p=2975 u=sarthak n=ansible | PLAY RECAP ************************************************************************************************************************************************************************
2024-11-14 15:04:15,437 p=2975 u=sarthak n=ansible | v1                         : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-14 15:04:15,437 p=2975 u=sarthak n=ansible | v2                         : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-14 23:04:16,399 p=10138 u=sarthak n=ansible |  [ERROR]: User interrupted execution

2024-11-14 23:04:21,927 p=10156 u=sarthak n=ansible | PLAY [Execute system commands] ****************************************************************************************************************************************************
2024-11-14 23:04:21,930 p=10156 u=sarthak n=ansible | TASK [Gathering Facts] ************************************************************************************************************************************************************
2024-11-14 23:04:38,653 p=10156 u=sarthak n=ansible | [WARNING]: Platform linux on host v2 is using the discovered Python interpreter at /usr/bin/python3.11, but future installation of another Python interpreter could change the
meaning of that path. See https://docs.ansible.com/ansible-core/2.17/reference_appendices/interpreter_discovery.html for more information.

2024-11-14 23:04:38,653 p=10156 u=sarthak n=ansible | ok: [v2]
2024-11-14 23:04:38,660 p=10156 u=sarthak n=ansible | TASK [Run system commands and get output] *****************************************************************************************************************************************
2024-11-14 23:04:53,250 p=10156 u=sarthak n=ansible | ok: [v2]
2024-11-14 23:04:53,257 p=10156 u=sarthak n=ansible | TASK [Show the result] ************************************************************************************************************************************************************
2024-11-14 23:04:53,272 p=10156 u=sarthak n=ansible | ok: [v2] => {
    "result": {
        "changed": false,
        "failed": false,
        "result": {
            "Architecture": "x86_64",
            "Filesystem Disk Space": {
                "avail": "76G",
                "filesystem": "/dev/mapper/rhel-root",
                "mounted_on": "/",
                "size": "91G",
                "status": true,
                "use_percent": "17%",
                "used": "15G"
            },
            "Filesystem Type": "xfs",
            "Java Version": "java version \"1.8.0_421\"",
            "OS Release Info": {
                "os_name": "Red Hat Enterprise Linux",
                "os_version": "8.10"
            },
            "TIVsm-API64.x86_64.rpm": {
                "output": "Error: warning: TIVsm-API64.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID e58157a3: NOKEY\n\tpackage TIVsm-API64-8.1.24-0.x86_64 is already installed"
            },
            "TIVsm-APIcit.x86_64.rpm": {
                "output": "Error: warning: TIVsm-APIcit.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID e58157a3: NOKEY\n\tpackage TIVsm-APIcit-8.1.24-0.x86_64 is already installed"
            },
            "TIVsm-BA.x86_64.rpm": {
                "output": "Error: warning: TIVsm-BA.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID e58157a3: NOKEY\n\tpackage TIVsm-BA-8.1.24-0.x86_64 is already installed"
            },
            "TIVsm-BAcit.x86_64.rpm": {
                "output": "Error: warning: TIVsm-BAcit.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID e58157a3: NOKEY\n\tpackage TIVsm-BAcit-8.1.24-0.x86_64 is already installed"
            },
            "TIVsm-BAhdw.x86_64.rpm": {
                "output": "Error: warning: TIVsm-BAhdw.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID e58157a3: NOKEY\n\tpackage TIVsm-BAhdw-8.1.24-0.x86_64 is already installed"
            },
            "compatibility": {
                "compatible": true,
                "reason": "System is compatible."
            },
            "dsmc_message": "BA client installed successfully, but no specific errors detected.",
            "extract_result": {
                "changed": true,
                "msg": "Tar file extracted successfully."
            },
            "gskcrypt64-8.0.55.31.linux.x86_64.rpm": {
                "output": "Error: warning: gskcrypt64-8.0.55.31.linux.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 96e7c766: NOKEY\n\tpackage gskcrypt64-8.0-55.31.x86_64 is already installed"
            },
            "gskssl64-8.0.55.31.linux.x86_64.rpm": {
                "output": "Error: warning: gskssl64-8.0.55.31.linux.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 96e7c766: NOKEY\n\tpackage gskssl64-8.0-55.31.x86_64 is already installed"
            }
        }
    }
}
2024-11-14 23:04:53,281 p=10156 u=sarthak n=ansible | PLAY RECAP ************************************************************************************************************************************************************************
2024-11-14 23:04:53,281 p=10156 u=sarthak n=ansible | v2                         : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-18 09:58:23,287 p=12027 u=sarthak n=ansible | PLAY [Execute system commands] ****************************************************************************************************************************************************
2024-11-18 09:58:23,292 p=12027 u=sarthak n=ansible | TASK [Gathering Facts] ************************************************************************************************************************************************************
2024-11-18 09:58:39,577 p=12027 u=sarthak n=ansible | [WARNING]: Platform linux on host v2 is using the discovered Python interpreter at /usr/bin/python3.11, but future installation of another Python interpreter could change the
meaning of that path. See https://docs.ansible.com/ansible-core/2.17/reference_appendices/interpreter_discovery.html for more information.

2024-11-18 09:58:39,577 p=12027 u=sarthak n=ansible | ok: [v2]
2024-11-18 09:58:39,584 p=12027 u=sarthak n=ansible | TASK [Run system commands and get output] *****************************************************************************************************************************************
2024-11-18 09:58:47,745 p=12027 u=sarthak n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: cannot import name 'run_dsmc_command' from 'ansible.module_utils.install_ba_client_utils' (/tmp/ansible_install_ba_client_payload_xqra76o0/ansible_install_ba_client_payload.zip/ansible/module_utils/install_ba_client_utils.py)
2024-11-18 09:58:47,746 p=12027 u=sarthak n=ansible | fatal: [v2]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 9.11.69.84 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1731904120.489012-12051-36644908980761/AnsiballZ_install_ba_client.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1731904120.489012-12051-36644908980761/AnsiballZ_install_ba_client.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1731904120.489012-12051-36644908980761/AnsiballZ_install_ba_client.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.install_ba_client', init_globals=dict(_module_fqn='ansible.modules.install_ba_client', _modlib_path=modlib_path),\r\n  File \"<frozen runpy>\", line 226, in run_module\r\n  File \"<frozen runpy>\", line 98, in _run_module_code\r\n  File \"<frozen runpy>\", line 88, in _run_code\r\n  File \"/tmp/ansible_install_ba_client_payload_xqra76o0/ansible_install_ba_client_payload.zip/ansible/modules/install_ba_client.py\", line 3, in <module>\r\nImportError: cannot import name 'run_dsmc_command' from 'ansible.module_utils.install_ba_client_utils' (/tmp/ansible_install_ba_client_payload_xqra76o0/ansible_install_ba_client_payload.zip/ansible/module_utils/install_ba_client_utils.py)\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-18 09:58:47,748 p=12027 u=sarthak n=ansible | PLAY RECAP ************************************************************************************************************************************************************************
2024-11-18 09:58:47,748 p=12027 u=sarthak n=ansible | v2                         : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-18 09:59:23,366 p=12092 u=sarthak n=ansible | PLAY [Execute system commands] ****************************************************************************************************************************************************
2024-11-18 09:59:23,369 p=12092 u=sarthak n=ansible | TASK [Gathering Facts] ************************************************************************************************************************************************************
2024-11-18 09:59:34,588 p=12092 u=sarthak n=ansible | [WARNING]: Platform linux on host v2 is using the discovered Python interpreter at /usr/bin/python3.11, but future installation of another Python interpreter could change the
meaning of that path. See https://docs.ansible.com/ansible-core/2.17/reference_appendices/interpreter_discovery.html for more information.

2024-11-18 09:59:34,589 p=12092 u=sarthak n=ansible | ok: [v2]
2024-11-18 09:59:34,595 p=12092 u=sarthak n=ansible | TASK [Run system commands and get output] *****************************************************************************************************************************************
2024-11-18 10:00:16,344 p=12092 u=sarthak n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'tuple' object has no attribute 'get'
2024-11-18 10:00:16,345 p=12092 u=sarthak n=ansible | fatal: [v2]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 9.11.69.84 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1731904175.4814029-12113-278977070608101/AnsiballZ_install_ba_client.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1731904175.4814029-12113-278977070608101/AnsiballZ_install_ba_client.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1731904175.4814029-12113-278977070608101/AnsiballZ_install_ba_client.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.install_ba_client', init_globals=dict(_module_fqn='ansible.modules.install_ba_client', _modlib_path=modlib_path),\r\n  File \"<frozen runpy>\", line 226, in run_module\r\n  File \"<frozen runpy>\", line 98, in _run_module_code\r\n  File \"<frozen runpy>\", line 88, in _run_code\r\n  File \"/tmp/ansible_install_ba_client_payload_9k6a_jng/ansible_install_ba_client_payload.zip/ansible/modules/install_ba_client.py\", line 100, in <module>\r\n  File \"/tmp/ansible_install_ba_client_payload_9k6a_jng/ansible_install_ba_client_payload.zip/ansible/modules/install_ba_client.py\", line 89, in main\r\n  File \"/tmp/ansible_install_ba_client_payload_9k6a_jng/ansible_install_ba_client_payload.zip/ansible/module_utils/install_ba_client_utils.py\", line 304, in run_dsmc_command\r\nAttributeError: 'tuple' object has no attribute 'get'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-18 10:00:16,346 p=12092 u=sarthak n=ansible | PLAY RECAP ************************************************************************************************************************************************************************
2024-11-18 10:00:16,346 p=12092 u=sarthak n=ansible | v2                         : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-18 10:01:52,727 p=12160 u=sarthak n=ansible | PLAY [Execute system commands] ****************************************************************************************************************************************************
2024-11-18 10:01:52,730 p=12160 u=sarthak n=ansible | TASK [Gathering Facts] ************************************************************************************************************************************************************
2024-11-18 10:02:19,021 p=12160 u=sarthak n=ansible | [WARNING]: Platform linux on host v2 is using the discovered Python interpreter at /usr/bin/python3.11, but future installation of another Python interpreter could change the
meaning of that path. See https://docs.ansible.com/ansible-core/2.17/reference_appendices/interpreter_discovery.html for more information.

2024-11-18 10:02:19,022 p=12160 u=sarthak n=ansible | ok: [v2]
2024-11-18 10:02:19,028 p=12160 u=sarthak n=ansible | TASK [Run system commands and get output] *****************************************************************************************************************************************
2024-11-18 10:02:34,212 p=12160 u=sarthak n=ansible | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: argument of type 'int' is not iterable
2024-11-18 10:02:34,212 p=12160 u=sarthak n=ansible | fatal: [v2]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 9.11.69.84 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1731904340.0310268-12185-173863054330554/AnsiballZ_install_ba_client.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1731904340.0310268-12185-173863054330554/AnsiballZ_install_ba_client.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1731904340.0310268-12185-173863054330554/AnsiballZ_install_ba_client.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.install_ba_client', init_globals=dict(_module_fqn='ansible.modules.install_ba_client', _modlib_path=modlib_path),\r\n  File \"<frozen runpy>\", line 226, in run_module\r\n  File \"<frozen runpy>\", line 98, in _run_module_code\r\n  File \"<frozen runpy>\", line 88, in _run_code\r\n  File \"/tmp/ansible_install_ba_client_payload_j6q2oxgc/ansible_install_ba_client_payload.zip/ansible/modules/install_ba_client.py\", line 100, in <module>\r\n  File \"/tmp/ansible_install_ba_client_payload_j6q2oxgc/ansible_install_ba_client_payload.zip/ansible/modules/install_ba_client.py\", line 89, in main\r\n  File \"/tmp/ansible_install_ba_client_payload_j6q2oxgc/ansible_install_ba_client_payload.zip/ansible/module_utils/install_ba_client_utils.py\", line 313, in run_dsmc_command\r\nTypeError: argument of type 'int' is not iterable\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2024-11-18 10:02:34,213 p=12160 u=sarthak n=ansible | PLAY RECAP ************************************************************************************************************************************************************************
2024-11-18 10:02:34,213 p=12160 u=sarthak n=ansible | v2                         : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2024-11-18 10:02:55,081 p=12234 u=sarthak n=ansible | PLAY [Execute system commands] ****************************************************************************************************************************************************
2024-11-18 10:02:55,084 p=12234 u=sarthak n=ansible | TASK [Gathering Facts] ************************************************************************************************************************************************************
2024-11-18 10:03:08,526 p=12234 u=sarthak n=ansible | [WARNING]: Platform linux on host v2 is using the discovered Python interpreter at /usr/bin/python3.11, but future installation of another Python interpreter could change the
meaning of that path. See https://docs.ansible.com/ansible-core/2.17/reference_appendices/interpreter_discovery.html for more information.

2024-11-18 10:03:08,527 p=12234 u=sarthak n=ansible | ok: [v2]
2024-11-18 10:03:08,533 p=12234 u=sarthak n=ansible | TASK [Run system commands and get output] *****************************************************************************************************************************************
2024-11-18 10:03:27,476 p=12234 u=sarthak n=ansible | ok: [v2]
2024-11-18 10:03:27,485 p=12234 u=sarthak n=ansible | TASK [Show the result] ************************************************************************************************************************************************************
2024-11-18 10:03:27,501 p=12234 u=sarthak n=ansible | ok: [v2] => {
    "result": {
        "changed": false,
        "failed": false,
        "result": {
            "Architecture": "x86_64",
            "Filesystem Disk Space": {
                "avail": "77G",
                "filesystem": "/dev/mapper/rhel-root",
                "mounted_on": "/",
                "size": "91G",
                "status": true,
                "use_percent": "16%",
                "used": "15G"
            },
            "Filesystem Type": "xfs",
            "Java Version": "java version \"1.8.0_421\"",
            "OS Release Info": {
                "os_name": "Red Hat Enterprise Linux",
                "os_version": "8.10"
            },
            "compatibility": {
                "compatible": true,
                "reason": "System is compatible."
            },
            "extract_result": {
                "changed": true,
                "msg": "Tar file extracted successfully."
            },
            "install_results": {
                "/opt/baClient/TIVsm-API64.x86_64.rpm": {
                    "rc": 1,
                    "stderr": "warning: /opt/baClient/TIVsm-API64.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID e58157a3: NOKEY\n\tpackage TIVsm-API64-8.1.24-0.x86_64 is already installed\n",
                    "stdout": "Verifying...                          ########################################\nPreparing...                          ########################################\n"
                },
                "/opt/baClient/TIVsm-APIcit.x86_64.rpm": {
                    "rc": 1,
                    "stderr": "warning: /opt/baClient/TIVsm-APIcit.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID e58157a3: NOKEY\n\tpackage TIVsm-APIcit-8.1.24-0.x86_64 is already installed\n",
                    "stdout": "Verifying...                          ########################################\nPreparing...                          ########################################\n"
                },
                "/opt/baClient/TIVsm-BA.x86_64.rpm": {
                    "rc": 1,
                    "stderr": "warning: /opt/baClient/TIVsm-BA.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID e58157a3: NOKEY\n\tpackage TIVsm-BA-8.1.24-0.x86_64 is already installed\n",
                    "stdout": "Verifying...                          ########################################\nPreparing...                          ########################################\n"
                },
                "/opt/baClient/TIVsm-BAcit.x86_64.rpm": {
                    "rc": 1,
                    "stderr": "warning: /opt/baClient/TIVsm-BAcit.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID e58157a3: NOKEY\n\tpackage TIVsm-BAcit-8.1.24-0.x86_64 is already installed\n",
                    "stdout": "Verifying...                          ########################################\nPreparing...                          ########################################\n"
                },
                "/opt/baClient/TIVsm-BAhdw.x86_64.rpm": {
                    "rc": 1,
                    "stderr": "warning: /opt/baClient/TIVsm-BAhdw.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID e58157a3: NOKEY\n\tpackage TIVsm-BAhdw-8.1.24-0.x86_64 is already installed\n",
                    "stdout": "Verifying...                          ########################################\nPreparing...                          ########################################\n"
                }
            }
        }
    }
}
2024-11-18 10:03:27,510 p=12234 u=sarthak n=ansible | PLAY RECAP ************************************************************************************************************************************************************************
2024-11-18 10:03:27,510 p=12234 u=sarthak n=ansible | v2                         : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2024-11-18 10:07:38,182 p=12301 u=sarthak n=ansible | PLAY [Execute system commands] ****************************************************************************************************************************************************
2024-11-18 10:07:38,186 p=12301 u=sarthak n=ansible | TASK [Gathering Facts] ************************************************************************************************************************************************************
2024-11-18 10:08:00,546 p=12301 u=sarthak n=ansible | [WARNING]: Platform linux on host v2 is using the discovered Python interpreter at /usr/bin/python3.11, but future installation of another Python interpreter could change the
meaning of that path. See https://docs.ansible.com/ansible-core/2.17/reference_appendices/interpreter_discovery.html for more information.

2024-11-18 10:08:00,546 p=12301 u=sarthak n=ansible | ok: [v2]
2024-11-18 10:08:00,553 p=12301 u=sarthak n=ansible | TASK [Run system commands and get output] *****************************************************************************************************************************************
2024-11-18 10:08:44,806 p=12301 u=sarthak n=ansible | ok: [v2]
2024-11-18 10:08:44,813 p=12301 u=sarthak n=ansible | TASK [Show the result] ************************************************************************************************************************************************************
2024-11-18 10:08:44,828 p=12301 u=sarthak n=ansible | ok: [v2] => {
    "result": {
        "changed": false,
        "failed": false,
        "result": {
            "Architecture": "x86_64",
            "Filesystem Disk Space": {
                "avail": "78G",
                "filesystem": "/dev/mapper/rhel-root",
                "mounted_on": "/",
                "size": "91G",
                "status": true,
                "use_percent": "15%",
                "used": "13G"
            },
            "Filesystem Type": "xfs",
            "Java Version": "java version \"1.8.0_421\"",
            "OS Release Info": {
                "os_name": "Red Hat Enterprise Linux",
                "os_version": "8.10"
            },
            "compatibility": {
                "compatible": true,
                "reason": "System is compatible."
            },
            "extract_result": {
                "changed": true,
                "msg": "Tar file extracted successfully."
            },
            "install_results": {
                "/opt/baClient/TIVsm-API64.x86_64.rpm": {
                    "rc": 0,
                    "stderr": "warning: /opt/baClient/TIVsm-API64.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID e58157a3: NOKEY\n",
                    "stdout": "Verifying...                          ########################################\nPreparing...                          ########################################\nUpdating / installing...\nTIVsm-API64-8.1.24-0                  ########################################\n"
                },
                "/opt/baClient/TIVsm-APIcit.x86_64.rpm": {
                    "rc": 0,
                    "stderr": "warning: /opt/baClient/TIVsm-APIcit.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID e58157a3: NOKEY\n",
                    "stdout": "Verifying...                          ########################################\nPreparing...                          ########################################\nUpdating / installing...\nTIVsm-APIcit-8.1.24-0                 ########################################\n"
                },
                "/opt/baClient/TIVsm-BA.x86_64.rpm": {
                    "rc": 0,
                    "stderr": "warning: /opt/baClient/TIVsm-BA.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID e58157a3: NOKEY\n",
                    "stdout": "Verifying...                          ########################################\nPreparing...                          ########################################\nUpdating / installing...\nTIVsm-BA-8.1.24-0                     ########################################\n"
                },
                "/opt/baClient/TIVsm-BAcit.x86_64.rpm": {
                    "rc": 0,
                    "stderr": "warning: /opt/baClient/TIVsm-BAcit.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID e58157a3: NOKEY\n",
                    "stdout": "Verifying...                          ########################################\nPreparing...                          ########################################\nUpdating / installing...\nTIVsm-BAcit-8.1.24-0                  ########################################\n"
                },
                "/opt/baClient/TIVsm-BAhdw.x86_64.rpm": {
                    "rc": 0,
                    "stderr": "warning: /opt/baClient/TIVsm-BAhdw.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID e58157a3: NOKEY\n",
                    "stdout": "Verifying...                          ########################################\nPreparing...                          ########################################\nUpdating / installing...\nTIVsm-BAhdw-8.1.24-0                  ########################################\n"
                }
            }
        }
    }
}
2024-11-18 10:08:44,836 p=12301 u=sarthak n=ansible | PLAY RECAP ************************************************************************************************************************************************************************
2024-11-18 10:08:44,836 p=12301 u=sarthak n=ansible | v2                         : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
